services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        environment:
            - TZ=Etc/UTC
        ports:
            - "8443:8443" # HTTPS
            - "8123:8123" # DYNMAP
            - "19132:19132/udp" # BEDROCK
        volumes:
            - /home/mc/crafty/backups:/crafty/backups
            - /home/mc/crafty/logs:/crafty/logs
            - /home/mc/crafty/servers:/crafty/servers
            - /home/mc/crafty/config:/crafty/app/config
            - /home/mc/crafty/import:/crafty/import
    mc-router:
        image: itzg/mc-router
        restart: always
        environment:
            USE_PROXY_PROTOCOL: "true"
            MAPPING: |
                dori.mc.chililime.hu=crafty:25568
                sch.mc.chililime.hu=crafty:25565
        ports:
        - "25565:25565"
  
    database:
        image: 'postgres:17'
        restart: always
        ports:
            - 5432:5432

        volumes:
            - ./db-data:/var/lib/postgresql/data/

        env_file:
            - .env
