http:
  routers:
    mc-router:
      rule: "Host(`mc.gyurus.hu`)"
      entryPoints:
        - websecure
      service: mc-service
      middlewares:
        - mc-ratelimit
      tls:
        certResolver: letsencrypt

  middlewares:
    mc-ratelimit:
      rateLimit:
        average: 10
        period: 1s
        burst: 20

  services:
    mc-service:
      loadBalancer:
        serversTransport: mc-transport
        servers:
          - url: "https://10.1.1.3:8443"

  serversTransports:
    mc-transport:
      insecureSkipVerify: true


tcp:
  routers:
    minecraft:
      entryPoints:
        - minecraft
      rule: "HostSNI(`*`)"
      service: minecraft-servers

  services:
    minecraft-servers:
      loadBalancer:
        servers:
          - address: "10.1.1.3:25565"